### ISSUE TITLE
Issue with Forge multiparts dupping

### ISSUE THREAD

**Issue by Dannerick** [UniversalLP/XACT#18]
When I craft multipart hollow covers from solid covers, the Xact crafter only uses 1 of the covers, not the recipes 8 covers. This is a serious dup issue.

**Comment by univrsal** [comment]
That is so random. I hope I can rewrite the Crafting Handler for xact 2.
Oh well I'll see if I can find the issue

**Comment by Dannerick** [comment]
I have seen a few other instances of the crafter not using all the materials. It seems to only occur in recipes where there is more than one of an item and the craft uses up just one. It only happens on a handful of recipes, but always occurs on the same recipe repeatedly, like the hollow cover issue above.

**Comment by Dannerick** [comment]
I was able to identify the problem and put in a pull request with the fix. The issue was with nbt data not being properly compared and the required item counts not being calculated correctly.
