### ISSUE TITLE
Config ignoredBlocks not working with multiple items

### ISSUE THREAD

**Issue by Loonacy** [UniversalLP/XACT#21]
I found a dupe bug with the RFTools Crafter, and i wanted to add it to the "ignoredBlocks" config.
When i put in just one item it works as expected and ignores the inventory.  But when i put multiple items in the ignoredBlocks, it doesn't ignore the inventory.

This works:

```
customization {
    # Make the crafter ignore blocks [default: []]
    S:ignoredBlocks <
        rftools:crafterBlock2:0
     >
}
```

This doesn't work:

```
customization {
    # Make the crafter ignore blocks [default: []]
    S:ignoredBlocks <
        rftools:crafterBlock1:0
        rftools:crafterBlock2:0
        rftools:crafterBlock3:0
     >
}
```

**Comment by JasonMcRay** [comment]
I can confirm that this doesn't work. @UniversalLP I know that you are quite busy, but ignoring blocks is essential to prevent crashes with incompatible mods.

For example when I have Production Table (from Steves Workshop mod) next to xact crafter, there are items in the crafting grid and I try to craft something in the XACT crafter that has the items in the Production table grid. I got a crash :(
