### ISSUE TITLE
NO NEI Template-Button

### ISSUE THREAD

**Issue by Nightreaver** [UniversalLP/XACT#3]
Hello

Your workbenches dont have the "helper button" for show/placing items directly from NEI on the workbench. You have to remember everything, which is sometimes... impossibru :/ (depending on time and day of week ;) )

Can you please add support for this? Its the small questionmark that you got when you use a normal work bench

**Comment by univrsal** [comment]
![Image of Yaktocat](http://i.imgur.com/eFIwDGj.gif)
That should be it. I also added in the "Recipe" tooltip when you hover over the arrow.
You can download the new version [here](https://drive.google.com/open?id=0B2Xx16RPrU-IV254TDYtbWxPaGM&authuser=0)

**Comment by Nightreaver** [comment]
Okay... the Questionmark is working now...

Shift + ? - doesn't place the items in the grid automatically... at least its not working for me, am I doing it wrong? (tested with xact recipe and normal wooden chest)

Also, it seem that the recipe for the xact workbench isnt working anymore?! Do i have to reset the config or something? i have installed the 1.5.2c

**Comment by UniversalLP** [comment]
Hmm. I couldn't reproduce that bug. It works all fine here. Both the XACT version of the vanilla crafting table and the XACT crafter. The only think that might be it is your NEI/CodechickenCore version. I tried both the recommended and latest version and both worked.
It might also be another mod that conflicts but that is rather unlikely

**Comment by UniversalLP** [comment]
Hmm. I couldn't reproduce that bug. It works all fine here. Both the XACT version of the vanilla crafting table and the XACT crafter. The only think that might be it is your NEI/CodechickenCore version. I tried both the recommended and latest version and both worked.
It might also be another mod that conflicts but that is rather unlikely

**Comment by UniversalLP** [comment]
Hmm. I couldn't reproduce that bug. It works all fine here. Both the XACT version of the vanilla crafting table and the XACT crafter. The only think that might be it is your NEI/CodechickenCore version. I tried both the recommended and latest version and both worked.
It might also be another mod that conflicts but that is rather unlikely

**Comment by univrsal** [comment]
Hmm. I couldn't reproduce that bug. It works all fine here. Both the XACT version of the vanilla crafting table and the XACT crafter. The only think that might be it is your NEI/CodechickenCore version. I tried both the recommended and latest version and both worked.
It might also be another mod that conflicts but that is rather unlikely

**Comment by UniversalLP** [comment]
Hmm. I couldn't reproduce that bug. It works all fine here. Both the XACT version of the vanilla crafting table and the XACT crafter. The only think that might be it is your NEI/CodechickenCore version. I tried both the recommended and latest version and both worked.
It might also be another mod that conflicts but that is rather unlikely

**Comment by UniversalLP** [comment]
Hmm. I couldn't reproduce that bug. It works all fine here. Both the XACT version of the vanilla crafting table and the XACT crafter. The only think that might be it is your NEI/CodechickenCore version. I tried both the recommended and latest version and both worked.
It might also be another mod that conflicts but that is rather unlikely

**Comment by Nightreaver** [comment]
You're right... dont know what it was in singleplayer... in multiplayer everything is fine!
