### ISSUE TITLE
Consumes magical Crops infusion Stones

### ISSUE THREAD

**Issue by Nightreaver** [UniversalLP/XACT#4]
Hello 

Playing with Magical Crops and XACT makes the infusion stones disappear at the xact workbench.
The stones are part of the recipe and you "get it back" after you have used it to make the bigger essences.

When you do that with XACT workbench... they are gone. 

magicalcrops-1.7.10_0.1.jar
XACT-1.7.10-0.5.2c.jar

Cheers

**Comment by univrsal** [comment]
Uhh... Did you look on curseforge? There's a version 4.0.0 Public beta for Magical Crops. Using that I have no problems crafting with the Infusion stone

**Comment by Nightreaver** [comment]
Yeah i know... but its.. 4 .. beta.. and it had problems with mods i use... wasn't really sure if using this is a good idea. but then it's okay and I will try to switch to the new verson next time :)

**Comment by univrsal** [comment]
Ok it seems like I misunderstood you. By XACT Workbench i think of the workbench that is added by XACT which looks exactly like the vanilla one but it keeps it's items. You meant the XACT crafter, right? Because with the crafter it seems like the Infusion stone is disappearing

**Comment by univrsal** [comment]
![Gif](http://i.imgur.com/kMsW6kY.gif)
Soo that is fixed now :D 
[Here](https://drive.google.com/file/d/0B2Xx16RPrU-IN2k1UG9NeXlqLW8/view?usp=sharing) you can get the fixed version
