### ISSUE TITLE
Xact Crafter in creative

### ISSUE THREAD

**Issue by JasonMcRay** [UniversalLP/XACT#6]
i am not sure if it is intended, but when I am in creative and I am using XACT Crafter for crafting something, it does not consume the items in the storage area and gives me the crafted item for free.

i dont even need the items to be present in the storage area. I can just click on NEI questionmark to get the recipe in, and then pull out any number of the items i want

**Comment by univrsal** [comment]
Yeah that's intended since players in creative would have infinite resources anyway. You'll notice that the square around crafting chips is blue indicating that no matter if you have the resources you can still craft it.

**Comment by JasonMcRay** [comment]
@UniversalLP could you add a config option to enable/disable this feature? Sometimes I am in creative, but not for the "infinite" items, but to test something in my normal world, but i dont want to "cheat" in the items.

For example i am testing few recipes, that I am changing with minetweaker if they work properly (like if crafting with bucket of water will empty the bucket, or with tool where the tool should take durability damage). Its slightly annyoing to switch back and forth with creative/normal.

Or maybe even better idea than config option... When player will be in creative and will open XACT Crafter there will be button on top with C, which when pressed will enable/disable this behaviour.

Thank you for consideration :)
