### ISSUE TITLE
Crafter items in storage does not dissapear on use

### ISSUE THREAD

**Issue by JasonMcRay** [UniversalLP/XACT#7]
When you craft items within XACT Crafter and it pulls items from nearby inventories and its own storage, the internal storage of Crafter does not update immediately. I need to close the interface, pick or anyhow else force the sync happen.

Reproduce:
1) Put a XACT crafter and chest next to it
2) Put 2 wood planks into Crafter internal storage
3) Put 2 wood planks into chest
4) In Crafter set the recipe to make crafting table
5) Pull out the crafting table from the output
6) Items inside the Crafter will still appear present.
7) If you try to pick them up, sort the inventory using Inventory Tweaks or just close the Crafter interface and reopen it, the Items properly dissapear.

**Comment by JasonMcRay** [comment]
I dont remember but was this fixed? I am looking in my mail if there was some message but cant find anything.... If it was... well it is not :)

**Comment by univrsal** [comment]
Huh well It seemed to work for me
Last time I checked
Ok well I thought it was fixed since the bug only occurs like half of the time

**Comment by univrsal** [comment]
Well this will probably have to wait until friday. It's a pretty random issue. Doesn't occure in creative and in survival only every second time I try it

**Comment by JasonMcRay** [comment]
Its happening everytime for me :)

**Comment by univrsal** [comment]
Oh well I _think_ I got it. I tried it about 16 times and it didn't occur.
If it's still not fixed just tell me.
