### ISSUE TITLE
Crash with Controls menu

### ISSUE THREAD

**Issue by JasonMcRay** [UniversalLP/XACT#8]
The new version of XACT (0.5.3b) added this config line:
B:enableKeybinds=false

When this is set to false, it causes client to crash with: http://pastebin.com/aK5fHrxh

When set to true, it no longer crashes.

**Comment by univrsal** [comment]
Gonna Look into that
Btw thanks for the thorough testing and reporting the bugs :D

**Comment by JasonMcRay** [comment]
No worries :) Its the least I can do as a thank you for taking over this mod :)

Forgot to add, that the crash happens when I open options/keybinds menu

**Comment by univrsal** [comment]
Fixed. I also added a config option for the free crafting when in creative.
The last bug I currently know about is with the magical wood. I'm not sure what to do with it since it's a pretty special recipe.
What do you think would be better
Blacklisting that recipe or allowing the player to craft it but only accepting books as resources if they have the same enchantment

**Comment by JasonMcRay** [comment]
What exactly is the bug with magical wood?

**Comment by univrsal** [comment]
Currently you can specify in the grid a recipe which for example uses four Enchanted books with Sharpness V which will result in a high amount of Magical Wood.
But the crafter accepts any enchanted book meaning that you can use for example four Protection I books and get the amount of Magical Wood as if you would've used Sharpness V books:

![Screenshot](http://i.imgur.com/CphfhpS.png?1)

**Comment by JasonMcRay** [comment]
Oh I see... Yea ExU is using special code for this recipe. I had also issues with this crafting recipe and gregtech. It seems that it accepts any enchanted items, and depending on how strong is the enchantment it produces that number of wood. Problem is, that it accepts also GT tools, which comes natively with enchantments and they are not used in the crafting process.

Accepting only the items put in the grid with the same enchantment is the go in here.

**Comment by univrsal** [comment]
Ok, so I just found out that that is a visual bug. You actually get the right amount it just shows the amount that you would get when using the exact items that are set in the crafting grid.
Hopefully I can get it to show right amount

**Comment by JasonMcRay** [comment]
oh nice :)

2015-09-10 20:35 GMT+02:00 UniversalLP notifications@github.com:
